"""스페이스AI 스톡랩 — 유니콘 평가 후보 풀 (60종).

출처: research/unicorn_research.md §3 (미국 20 / 한국 20 / 중국 20).
후보는 "자주 거론되는" 종목 모음일 뿐 통과 보장이 아니다.
탭 노출은 오직 갱신 시점 점수(65+)로 결정된다 (리서치 §5-5).

필드:
  ticker      Yahoo Finance 형식 ("BRK.B", "105560.KS", "0883.HK")
  name/nameEn 한국어/영어 표기
  market      "US" | "KR" | "CN"
  currency    "USD" | "KRW" | "HKD" | "CNY"
  theme       프론트 분류용 태그
  description 한 줄 소개 (후보 사유 요약)
  financial   금융 섹터 힌트 (yfinance sector 조회 실패 시 폴스백)
  sourceNotes 후보 선정 근거 출처
"""

CANDIDATES: list[dict] = [
    # ── 미국 (20) ────────────────────────────────────────────
    {"ticker": "BRK.B", "name": "버크셔 해서웨이 B", "nameEn": "Berkshire Hathaway B",
     "market": "US", "currency": "USD", "theme": ["지주", "가치주"],
     "description": "버핏의 지주회사. 순현금 $268B의 재무 정점, PE 14.5·PB 1.44(조사 시점).",
     "financial": True,
     "sourceNotes": ["stockanalysis.com 실측 (2026-07)"]},
    {"ticker": "GOOGL", "name": "알파벳", "nameEn": "Alphabet",
     "market": "US", "currency": "USD", "theme": ["빅테크", "AI"],
     "description": "버크셔가 2025 Q3에 $4.3B 신규 매수한 빅테크 최저 밸류.",
     "financial": False,
     "sourceNotes": ["Rule One Investing", "Benzinga"]},
    {"ticker": "CVX", "name": "셰브론", "nameEn": "Chevron",
     "market": "US", "currency": "USD", "theme": ["에너지", "배당"],
     "description": "버크셔 상위 5 보유, 에너지 대형 배당주.",
     "financial": False,
     "sourceNotes": ["LevelFields 13F 정리"]},
    {"ticker": "OXY", "name": "옥시덴탈", "nameEn": "Occidental Petroleum",
     "market": "US", "currency": "USD", "theme": ["에너지"],
     "description": "버크셔 지분 28%, OxyChem 매각 대금으로 부채 감축.",
     "financial": False,
     "sourceNotes": ["Morningstar/MarketWatch"]},
    {"ticker": "BAC", "name": "뱅크오브아메리카", "nameEn": "Bank of America",
     "market": "US", "currency": "USD", "theme": ["금융", "은행"],
     "description": "버크셔 상위 보유 대형 은행(일부 축소에도 잔존).",
     "financial": True,
     "sourceNotes": ["LevelFields", "Kiplinger"]},
    {"ticker": "AXP", "name": "아메리칸 익스프레스", "nameEn": "American Express",
     "market": "US", "currency": "USD", "theme": ["금융", "결제"],
     "description": "버크셔 최상위 보유 우량 금융.",
     "financial": True,
     "sourceNotes": ["LevelFields"]},
    {"ticker": "KO", "name": "코카콜라", "nameEn": "Coca-Cola",
     "market": "US", "currency": "USD", "theme": ["소비재", "배당"],
     "description": "버크셔 장기 보유, 배당 귀족주.",
     "financial": False,
     "sourceNotes": ["LevelFields"]},
    {"ticker": "MCO", "name": "묶디스", "nameEn": "Moody's",
     "market": "US", "currency": "USD", "theme": ["금융", "신용평가"],
     "description": "버크셔 보유, 고ROE·독점적 신용평가.",
     "financial": True,
     "sourceNotes": ["LevelFields"]},
    {"ticker": "VZ", "name": "버라이즌", "nameEn": "Verizon",
     "market": "US", "currency": "USD", "theme": ["통신", "배당"],
     "description": "버크셔 top10, 고배당 통신.",
     "financial": False,
     "sourceNotes": ["LevelFields top10"]},
    {"ticker": "CB", "name": "처브", "nameEn": "Chubb",
     "market": "US", "currency": "USD", "theme": ["금융", "보험"],
     "description": "버크셔 top10 손해보험사.",
     "financial": True,
     "sourceNotes": ["Caproasia 13F 정리"]},
    {"ticker": "SHEL", "name": "셸", "nameEn": "Shell",
     "market": "US", "currency": "USD", "theme": ["에너지", "배당"],
     "description": "FCF 수익률 13.2%, 내재가치 대비 42.9% 할인, D/E 41.3%.",
     "financial": False,
     "sourceNotes": ["ValueSense 저평가 에너지 2025"]},
    {"ticker": "TTE", "name": "토탈에너지", "nameEn": "TotalEnergies",
     "market": "US", "currency": "USD", "theme": ["에너지", "배당"],
     "description": "유럽 에너지 저평가 2순위.",
     "financial": False,
     "sourceNotes": ["ValueSense 저평가 에너지 2025"]},
    {"ticker": "BMY", "name": "브리스톨마이어스 스큅", "nameEn": "Bristol-Myers Squibb",
     "market": "US", "currency": "USD", "theme": ["제약", "헬스케어"],
     "description": "모닝스타: 2025년 예상이익의 8배, 파이프라인 저평가.",
     "financial": False,
     "sourceNotes": ["Morningstar"]},
    {"ticker": "FIS", "name": "피델리티내셔널", "nameEn": "Fidelity National Information",
     "market": "US", "currency": "USD", "theme": ["핀테크", "금융IT"],
     "description": "DCF 공정가치 대비 32% 할인, 이익성장 23.7% 전망.",
     "financial": False,
     "sourceNotes": ["Simply Wall St via Webull"]},
    {"ticker": "UMBF", "name": "UMB파이낸셜", "nameEn": "UMB Financial",
     "market": "US", "currency": "USD", "theme": ["금융", "지방은행"],
     "description": "DCF 공정가치 대비 ~49% 할인 리스트 상시.",
     "financial": True,
     "sourceNotes": ["Simply Wall St via Webull"]},
    {"ticker": "GILD", "name": "길리어드", "nameEn": "Gilead Sciences",
     "market": "US", "currency": "USD", "theme": ["제약", "바이오"],
     "description": "저PER·고배당 제약 빈출 후보 (실측 검증 필요).",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "PFE", "name": "화이자", "nameEn": "Pfizer",
     "market": "US", "currency": "USD", "theme": ["제약", "배당"],
     "description": "고배당 제약, 백신 급감 후 밸류 리셋 (빈출 후보).",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "MO", "name": "알트리아", "nameEn": "Altria",
     "market": "US", "currency": "USD", "theme": ["담초", "배당"],
     "description": "배당 6~8% 니코틴 캐시카우 (배당 함정 T4 검증 필요).",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "GM", "name": "제너럴 모터스", "nameEn": "General Motors",
     "market": "US", "currency": "USD", "theme": ["자동차", "경기민감"],
     "description": "PER 5~7배 대표 경기 저평가주 (빈출 후보).",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "C", "name": "시티그룹", "nameEn": "Citigroup",
     "market": "US", "currency": "USD", "theme": ["금융", "은행"],
     "description": "PBR 0.7 전후 대형 은행 (빈출 후보).",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},

    # ── 한국 (20) ────────────────────────────────────────────
    {"ticker": "105560.KS", "name": "KB금융", "nameEn": "KB Financial Group",
     "market": "KR", "currency": "KRW", "theme": ["금융", "밸류업"],
     "description": "밸류업 대장: 시총 60조·PBR 1배 돌파(2026-02), ROE 9%대·배당성향 27%.",
     "financial": True,
     "sourceNotes": ["이데일리", "NH·현대차증권 리포트 인용"]},
    {"ticker": "055550.KS", "name": "신한지주", "nameEn": "Shinhan Financial Group",
     "market": "KR", "currency": "KRW", "theme": ["금융", "밸류업"],
     "description": "순이익 5.4조·주당배당 740원, NIM 개선.",
     "financial": True,
     "sourceNotes": ["경제이야기", "뉴스스페이스"]},
    {"ticker": "086790.KS", "name": "하나금융지주", "nameEn": "Hana Financial Group",
     "market": "KR", "currency": "KRW", "theme": ["금융", "배당"],
     "description": "PER 4~5배·PBR 0.3~0.4배·배당수익률 6%+ 저평가 우량주.",
     "financial": True,
     "sourceNotes": ["천안스카이에듀 블로그"]},
    {"ticker": "024110.KS", "name": "기업은행", "nameEn": "IBK",
     "market": "KR", "currency": "KRW", "theme": ["금융", "배당"],
     "description": "영업이익 1000대 7위, 저PER 고배당 조건 충족 사례로 반복 인용.",
     "financial": True,
     "sourceNotes": ["뉴스스페이스", "머니마인드"]},
    {"ticker": "138040.KS", "name": "메리츠금융지주", "nameEn": "Meritz Financial Group",
     "market": "KR", "currency": "KRW", "theme": ["금융", "주주환원"],
     "description": "수익성 우수 + 주주친화 정책의 금융 대안주.",
     "financial": True,
     "sourceNotes": ["머니마인드"]},
    {"ticker": "000810.KS", "name": "삼성화재", "nameEn": "Samsung Fire & Marine",
     "market": "KR", "currency": "KRW", "theme": ["금융", "보험"],
     "description": "영업이익 1000대 10위, 보험 이익 안정.",
     "financial": True,
     "sourceNotes": ["뉴스스페이스"]},
    {"ticker": "005930.KS", "name": "삼성전자", "nameEn": "Samsung Electronics",
     "market": "KR", "currency": "KRW", "theme": ["반도체", "대형주"],
     "description": "영업이익 2위, 메모리 업황 회복 + PBR 1배 전후.",
     "financial": False,
     "sourceNotes": ["뉴스스페이스"]},
    {"ticker": "000660.KS", "name": "SK하이닉스", "nameEn": "SK Hynix",
     "market": "KR", "currency": "KRW", "theme": ["반도체", "HBM"],
     "description": "영업이익 1위(2년 연속), HBM 독주 — 가치+성장 겸비(변동성 큼).",
     "financial": False,
     "sourceNotes": ["뉴스스페이스"]},
    {"ticker": "000270.KS", "name": "기아", "nameEn": "Kia",
     "market": "KR", "currency": "KRW", "theme": ["자동차", "저PER"],
     "description": "영업이익 4위, 저PER 자동차 대표.",
     "financial": False,
     "sourceNotes": ["뉴스스페이스"]},
    {"ticker": "005380.KS", "name": "현대차", "nameEn": "Hyundai Motor",
     "market": "KR", "currency": "KRW", "theme": ["자동차", "주주환원"],
     "description": "영업이익 6위, 저PER·주주환원 확대.",
     "financial": False,
     "sourceNotes": ["뉴스스페이스"]},
    {"ticker": "012330.KS", "name": "현대모비스", "nameEn": "Hyundai Mobis",
     "market": "KR", "currency": "KRW", "theme": ["자동차부품"],
     "description": "PBR·EPS 기준 저평가 우량주 TOP5 선정.",
     "financial": False,
     "sourceNotes": ["econsis"]},
    {"ticker": "000880.KS", "name": "한화", "nameEn": "Hanwha",
     "market": "KR", "currency": "KRW", "theme": ["지주", "방산"],
     "description": "지배구조 개선 기대 지주사 저평가 1순위.",
     "financial": False,
     "sourceNotes": ["econsis"]},
    {"ticker": "294870.KS", "name": "HDC", "nameEn": "HDC Holdings",
     "market": "KR", "currency": "KRW", "theme": ["지주", "건설"],
     "description": "지주사 저평가 TOP5.",
     "financial": False,
     "sourceNotes": ["econsis"]},
    {"ticker": "011780.KS", "name": "금호석유화학", "nameEn": "Kumho Petrochemical",
     "market": "KR", "currency": "KRW", "theme": ["화학", "경기민감"],
     "description": "저PBR 화학 TOP5.",
     "financial": False,
     "sourceNotes": ["econsis"]},
    {"ticker": "298020.KS", "name": "효성티앤씨", "nameEn": "Hyosung TNC",
     "market": "KR", "currency": "KRW", "theme": ["화학", "섬유"],
     "description": "저평가 우량주 TOP5.",
     "financial": False,
     "sourceNotes": ["econsis"]},
    {"ticker": "084010.KS", "name": "대한제강", "nameEn": "Daehan Steel",
     "market": "KR", "currency": "KRW", "theme": ["철강", "배당"],
     "description": "PBR<1 + PER 5~10 + 배당 5%+ 3조건 충족 사례.",
     "financial": False,
     "sourceNotes": ["머니마인드", "인베스팅닷컴 코스피 구성"]},
    {"ticker": "006260.KS", "name": "LS", "nameEn": "LS Corp",
     "market": "KR", "currency": "KRW", "theme": ["지주", "전선"],
     "description": "저평가 고배당 지주.",
     "financial": False,
     "sourceNotes": ["머니마인드"]},
    {"ticker": "003570.KS", "name": "SNT중공업", "nameEn": "SNT Heavy Industries",
     "market": "KR", "currency": "KRW", "theme": ["방산", "중공업"],
     "description": "국방 테마 + 저평가.",
     "financial": False,
     "sourceNotes": ["머니마인드", "종목코드 확인"]},
    {"ticker": "123890.KS", "name": "한국자산신탁", "nameEn": "Korea Asset In Trust",
     "market": "KR", "currency": "KRW", "theme": ["부동산신탁", "배당"],
     "description": "배당성향 90% 이상 부동산신탁.",
     "financial": True,
     "sourceNotes": ["머니마인드"]},
    {"ticker": "003690.KS", "name": "코리안리", "nameEn": "Korean Re",
     "market": "KR", "currency": "KRW", "theme": ["금융", "재보험"],
     "description": "재보험 안정 실적 + 꾸준한 배당.",
     "financial": True,
     "sourceNotes": ["머니마인드"]},

    # ── 중국 (홍콩 15 + A주 5 = 20) ──────────────────────────
    {"ticker": "9988.HK", "name": "알리바바", "nameEn": "Alibaba Group",
     "market": "CN", "currency": "HKD", "theme": ["전자상거래", "클우드"],
     "description": "전자상거래 FCF 창출 + 대규모 자사주; 목표가 상향 커버리지.",
     "financial": False,
     "sourceNotes": ["Morningstar", "SPDBI 리포트"]},
    {"ticker": "0700.HK", "name": "텐센트", "nameEn": "Tencent",
     "market": "CN", "currency": "HKD", "theme": ["게임", "인터넷"],
     "description": "GARP 대표: 견고한 FCF + 게임/광고 성장.",
     "financial": False,
     "sourceNotes": ["stock_universe.md"]},
    {"ticker": "9618.HK", "name": "징둥", "nameEn": "JD.com",
     "market": "CN", "currency": "HKD", "theme": ["전자상거래", "물류"],
     "description": "forward PER 8.24배(업종 평균 19.25배 대비), $5B 자사주 + 배당 32% 인상.",
     "financial": False,
     "sourceNotes": ["AInvest"]},
    {"ticker": "PDD", "name": "PDD홀딩스", "nameEn": "PDD Holdings",
     "market": "CN", "currency": "USD", "theme": ["전자상거래"],
     "description": "forward PER 9.17배 (미국 상장 중국 ADR).",
     "financial": False,
     "sourceNotes": ["AInvest"]},
    {"ticker": "9888.HK", "name": "바이두", "nameEn": "Baidu",
     "market": "CN", "currency": "HKD", "theme": ["인터넷", "AI"],
     "description": "저PER 인터넷 빈출 후보.",
     "financial": False,
     "sourceNotes": ["stock_universe.md"]},
    {"ticker": "9999.HK", "name": "넷이즈", "nameEn": "NetEase",
     "market": "CN", "currency": "HKD", "theme": ["게임"],
     "description": "순현금 풍부한 게임 캐시카우 (빈출 후보).",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "0941.HK", "name": "차이나모바일", "nameEn": "China Mobile",
     "market": "CN", "currency": "HKD", "theme": ["통신", "고배당"],
     "description": "중특평(中特估) 고배당 통신 SOE 대표.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출", "뉴스핌 GAM"]},
    {"ticker": "0883.HK", "name": "CNOOC", "nameEn": "CNOOC",
     "market": "CN", "currency": "HKD", "theme": ["에너지", "고배당"],
     "description": "PE 6.1배·ROE 15.4%·배당 5~7%·유동비율 3.24 — 3축 표본.",
     "financial": False,
     "sourceNotes": ["companiesmarketcap", "Wisesheets", "Digrin"]},
    {"ticker": "1088.HK", "name": "차이나신화에너지", "nameEn": "China Shenhua Energy",
     "market": "CN", "currency": "HKD", "theme": ["석탄", "고배당"],
     "description": "고배당 석탄 SOE, 배당성향 높음.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "0939.HK", "name": "중국건설은행", "nameEn": "CCB",
     "market": "CN", "currency": "HKD", "theme": ["금융", "은행"],
     "description": "PBR 0.6 이하 + 배당 6% 전후 대형은행.",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "1398.HK", "name": "공상은행", "nameEn": "ICBC",
     "market": "CN", "currency": "HKD", "theme": ["금융", "은행"],
     "description": "세계 최대 은행, 저PBR 고배당.",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "2318.HK", "name": "핑안보험", "nameEn": "Ping An Insurance",
     "market": "CN", "currency": "HKD", "theme": ["금융", "보험"],
     "description": "저PBR 보험 대표, 배당 회복.",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "0386.HK", "name": "시노펙", "nameEn": "Sinopec",
     "market": "CN", "currency": "HKD", "theme": ["석유화학", "고배당"],
     "description": "고배당 석유화학 SOE.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "0728.HK", "name": "차이나텔레콤", "nameEn": "China Telecom",
     "market": "CN", "currency": "HKD", "theme": ["통신", "배당성장"],
     "description": "배당 성장 명시 통신 SOE.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "1211.HK", "name": "BYD", "nameEn": "BYD",
     "market": "CN", "currency": "HKD", "theme": ["전기차", "GARP"],
     "description": "GARP: EV 1위 + 이익 성장.",
     "financial": False,
     "sourceNotes": ["stock_universe.md"]},
    {"ticker": "600519.SS", "name": "구이저우마오타이", "nameEn": "Kweichow Moutai",
     "market": "CN", "currency": "CNY", "theme": ["주류", "퀄리티"],
     "description": "ROE 30%대 퀄리티 표본, 소비 침체로 밸류 리셋.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "600036.SS", "name": "초상은행", "nameEn": "China Merchants Bank",
     "market": "CN", "currency": "CNY", "theme": ["금융", "은행"],
     "description": "중국 최우량 은행, PBR ~1배의 프리미엄 저평가.",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "600900.SS", "name": "창장전력", "nameEn": "China Yangtze Power",
     "market": "CN", "currency": "CNY", "theme": ["유틸리티", "배당"],
     "description": "수력 발전 안정 배당, 채권 유사 성격.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "000333.SZ", "name": "메이디", "nameEn": "Midea Group",
     "market": "CN", "currency": "CNY", "theme": ["가전", "GARP"],
     "description": "ROE 20%대 가전 GARP, 글로벌 배당 확대.",
     "financial": False,
     "sourceNotes": ["스크리너 빈출"]},
    {"ticker": "601318.SS", "name": "핑안보험 A", "nameEn": "Ping An Insurance A",
     "market": "CN", "currency": "CNY", "theme": ["금융", "보험"],
     "description": "H주 대비 할인/프리미엄 비교용 A주 표본.",
     "financial": True,
     "sourceNotes": ["스크리너 빈출"]},
]

assert len(CANDIDATES) == 60, f"후보 풀은 60종이어야 함 (현재 {len(CANDIDATES)})"
