"""스페이스AI 스톡랩 — 종목 유니버스 큐레이션 데이터.

큐레이션 근거: research/stock_universe.md
시세·재무 지표는 refresh_data.py가 yfinance로 수집하고,
여기서는 변하지 않는 수동 관리 필드(한국어 이름, 소개, 테마, 초보자 적합도,
밸류체인, 용어 예시 힌트)만 유지한다.
"""

# 각 항목 필드:
#   ticker          Yahoo Finance 형식 (코스피 .KS / 코스닥 .KQ / 홍콩 .HK / 상하이 .SS / 선전 .SZ)
#   name            한국어 표기
#   nameEn          영문 표기
#   market          "US" | "KR" | "CN"
#   currency        "USD" | "KRW" | "HKD" | "CNY"
#   theme           테마 태그 목록 (첫 번째 태그가 sectorAvg 그룹핑 기준)
#   description     한 줄 소개 (큐레이션)
#   beginnerFit     "good" | "caution" | "hard"
#   valueChain      밸류체인 위치
#   exampleTermHints  이 종목이 좋은 사례가 되는 glossary 용어 id 목록
#   extraRiskFlags  (선택) 수동 리스크 플래그

UNIVERSE: list[dict] = [
    # ── 미국 (9) ──────────────────────────────────────────────
    {
        "ticker": "NVDA",
        "name": "엔비디아",
        "nameEn": "NVIDIA",
        "market": "US",
        "currency": "USD",
        "theme": ["AI반도체"],
        "description": "AI 학습·추론용 GPU의 사실상 표준. 데이터센터 AI 칩의 절대 강자.",
        "beginnerFit": "good",
        "valueChain": "AI 칩 설계 (GPU)",
        "exampleTermHints": ["per", "roe", "operating-margin", "market-cap", "volume", "peg"],
    },
    {
        "ticker": "MSFT",
        "name": "마이크로소프트",
        "nameEn": "Microsoft",
        "market": "US",
        "currency": "USD",
        "theme": ["AI플랫폼", "클우드"],
        "description": "Azure 클라우드와 Copilot으로 기업용 AI를 파는 대표 AI 플랫폼 기업.",
        "beginnerFit": "good",
        "valueChain": "AI 클라우드·소프트웨어",
        "exampleTermHints": ["eps", "dividend-yield", "payout-ratio", "treasury-stock", "net-income", "roa"],
    },
    {
        "ticker": "GOOGL",
        "name": "알파벳(구글)",
        "nameEn": "Alphabet (Google)",
        "market": "US",
        "currency": "USD",
        "theme": ["AI플랫폼"],
        "description": "Gemini 모델·자체 TPU·검색/유튜브/클우드를 아우르는 풀스택 AI 기업.",
        "beginnerFit": "good",
        "valueChain": "AI 모델·TPU·서비스",
        "exampleTermHints": ["per", "market-cap", "revenue"],
    },
    {
        "ticker": "TSLA",
        "name": "테슬라",
        "nameEn": "Tesla",
        "market": "US",
        "currency": "USD",
        "theme": ["AI응용", "EV"],
        "description": "전기차 회사이지만 로보택시·FSD·옵티머스 로봇의 'AI 응용' 스토리 주식.",
        "beginnerFit": "caution",
        "valueChain": "자율주행·로봇 응용",
        "exampleTermHints": ["per", "beta", "week52", "short-selling"],
    },
    {
        "ticker": "PLTR",
        "name": "팔란티어",
        "nameEn": "Palantir Technologies",
        "market": "US",
        "currency": "USD",
        "theme": ["AI플랫폼", "데이터분석"],
        "description": "정부·기업용 데이터 분석 플랫폼(AIP). 고밸류에이션 AI 소프트웨어 대표.",
        "beginnerFit": "caution",
        "valueChain": "AI 데이터 분석 플랫폼",
        "exampleTermHints": ["per", "psr", "week52"],
    },
    {
        "ticker": "SPCX",
        "name": "스페이스X",
        "nameEn": "SpaceX",
        "market": "US",
        "currency": "USD",
        "theme": ["우주-발사체", "우주-위성통신", "AI"],
        "description": "팰컨9·스타십 발사체와 스타링크 위성인터넷. 2026년 6월 역대 최대 IPO로 상장.",
        "beginnerFit": "caution",
        "valueChain": "발사체·위성 인터넷",
        "exampleTermHints": ["float", "market-cap", "volume"],
        "extraRiskFlags": ["신규 상장 (유통물량 적음)"],
    },
    {
        "ticker": "RKLB",
        "name": "로켓랩",
        "nameEn": "Rocket Lab",
        "market": "US",
        "currency": "USD",
        "theme": ["우주-발사체", "우주-위성제조"],
        "description": "일렉트론 소형 발사체와 위성 제조. 민간 우주 2인자(뉴트론 개발 중).",
        "beginnerFit": "hard",
        "valueChain": "소형 발사체·위성 제조",
        "exampleTermHints": ["psr", "break-even", "revenue", "beta"],
    },
    {
        "ticker": "ASTS",
        "name": "AST스페이스모바일",
        "nameEn": "AST SpaceMobile",
        "market": "US",
        "currency": "USD",
        "theme": ["우주-위성통신"],
        "description": "일반 스마트폰에 직접 연결되는 위성 광대역망을 만드는 기업.",
        "beginnerFit": "hard",
        "valueChain": "위성 직결 통신망",
        "exampleTermHints": ["psr", "break-even", "beta"],
    },
    {
        "ticker": "LUNR",
        "name": "인튜이티브 머신스",
        "nameEn": "Intuitive Machines",
        "market": "US",
        "currency": "USD",
        "theme": ["우주-인프라", "달탐사"],
        "description": "NASA 달 착륙선(CLPS)을 수행하는 달 탐사·우주 인프라 기업.",
        "beginnerFit": "hard",
        "valueChain": "달 착륙선·우주 인프라",
        "exampleTermHints": ["break-even", "market-cap", "volume"],
    },
    # ── 한국 (8) ──────────────────────────────────────────────
    {
        "ticker": "005930.KS",
        "name": "삼성전자",
        "nameEn": "Samsung Electronics",
        "market": "KR",
        "currency": "KRW",
        "theme": ["AI반도체", "메모리"],
        "description": "메모리(DRAM/HBM)·파운드리·스마트폰의 글로벌 종합 반도체 기업.",
        "beginnerFit": "good",
        "valueChain": "메모리 반도체·파운드리",
        "exampleTermHints": ["pbr", "bps", "revenue", "operating-income", "foreign-ownership", "preferred-stock", "par-value"],
    },
    {
        "ticker": "000660.KS",
        "name": "SK하이닉스",
        "nameEn": "SK hynix",
        "market": "KR",
        "currency": "KRW",
        "theme": ["AI반도체", "HBM"],
        "description": "엔비디아향 HBM(고대역폭메모리) 세계 1위. AI 메모리 최대 수혜주.",
        "beginnerFit": "good",
        "valueChain": "HBM 메모리",
        "exampleTermHints": ["per", "roe", "operating-margin", "foreign-ownership"],
    },
    {
        "ticker": "035420.KS",
        "name": "네이버",
        "nameEn": "NAVER",
        "market": "KR",
        "currency": "KRW",
        "theme": ["AI플랫폼"],
        "description": "한국 대표 검색·커머스 플랫폼. 자체 LLM 하이퍼클로바X 보유.",
        "beginnerFit": "good",
        "valueChain": "AI 서비스·LLM",
        "exampleTermHints": ["per", "operating-margin", "revenue"],
    },
    {
        "ticker": "012450.KS",
        "name": "한화에어로스페이스",
        "nameEn": "Hanwha Aerospace",
        "market": "KR",
        "currency": "KRW",
        "theme": ["우주-발사체", "방위"],
        "description": "K9·천무 방산 대장. 누리호 엔진·항공엔진으로 우주에도 노출.",
        "beginnerFit": "good",
        "valueChain": "발사체 엔진·방산",
        "exampleTermHints": ["week52", "per", "market-cap"],
    },
    {
        "ticker": "047810.KS",
        "name": "한국항공우주(KAI)",
        "nameEn": "Korea Aerospace Industries",
        "market": "KR",
        "currency": "KRW",
        "theme": ["우주-위성제조", "방위"],
        "description": "KF-21·FA-50 전투기와 다목적실용위성을 만드는 국내 유일 항공우주 완제기 업체.",
        "beginnerFit": "good",
        "valueChain": "위성·항공기 완제품",
        "exampleTermHints": ["per", "revenue", "operating-margin"],
    },
    {
        "ticker": "079550.KS",
        "name": "LIG넥스원",
        "nameEn": "LIG Nex1",
        "market": "KR",
        "currency": "KRW",
        "theme": ["방위", "우주-위성통신"],
        "description": "천궁 유도무기·레이더·위성통신 단말을 만드는 방위산업체.",
        "beginnerFit": "caution",
        "valueChain": "유도무기·위성통신 단말",
        "exampleTermHints": ["week52", "volume", "beta"],
    },
    {
        "ticker": "272210.KS",
        "name": "한화시스템",
        "nameEn": "Hanwha Systems",
        "market": "KR",
        "currency": "KRW",
        "theme": ["우주-위성통신", "방위"],
        "description": "위성통신·레이더·C4I 체계. 저궤도 위성통신에 투자하는 방위전자 기업.",
        "beginnerFit": "caution",
        "valueChain": "위성통신·레이더",
        "exampleTermHints": ["per", "psr"],
    },
    {
        "ticker": "099320.KQ",
        "name": "쎄트렉아이",
        "nameEn": "Satrec Initiative",
        "market": "KR",
        "currency": "KRW",
        "theme": ["우주-위성제조"],
        "description": "소형 지구관측위성을 제조·수출하는 국내 대표 민간 위성 제조사(한화에어로스페이스 계열).",
        "beginnerFit": "hard",
        "valueChain": "소형 위성 제조",
        "exampleTermHints": ["market-cap", "volume", "float"],
    },
    # ── 중국 (9) ──────────────────────────────────────────────
    {
        "ticker": "9988.HK",
        "name": "알리바바",
        "nameEn": "Alibaba Group",
        "market": "CN",
        "currency": "HKD",
        "theme": ["AI플랫폼", "클우드"],
        "description": "중국 최대 이커머스·클우드 기업. 통이첸원(Qwen) 오픈소스 LLM 강자.",
        "beginnerFit": "good",
        "valueChain": "클우드·LLM",
        "exampleTermHints": ["per", "market-cap", "revenue"],
    },
    {
        "ticker": "0700.HK",
        "name": "텐센트",
        "nameEn": "Tencent",
        "market": "CN",
        "currency": "HKD",
        "theme": ["AI플랫폼"],
        "description": "위챗 슈퍼앱·게임·훈위안 LLM. 중국 대형주 중 가장 안정적인 편.",
        "beginnerFit": "good",
        "valueChain": "AI 플랫폼·게임",
        "exampleTermHints": ["per", "roe", "market-cap"],
    },
    {
        "ticker": "9888.HK",
        "name": "바이두",
        "nameEn": "Baidu",
        "market": "CN",
        "currency": "HKD",
        "theme": ["AI플랫폼", "자율주행"],
        "description": "어니봇 LLM·아폴로 자율주행·쿤룬신 AI 칩 자회사를 둔 검색 대장.",
        "beginnerFit": "caution",
        "valueChain": "LLM·자율주행·AI 칩",
        "exampleTermHints": ["pbr", "per", "psr"],
    },
    {
        "ticker": "1810.HK",
        "name": "샤오미",
        "nameEn": "Xiaomi",
        "market": "CN",
        "currency": "HKD",
        "theme": ["AIoT", "EV"],
        "description": "스마트폰·AIoT·전기차(SU7/YU7) 생태계를 만드는 하드웨어 기업.",
        "beginnerFit": "caution",
        "valueChain": "AIoT·전기차",
        "exampleTermHints": ["psr", "week52", "revenue"],
    },
    {
        "ticker": "1211.HK",
        "name": "BYD",
        "nameEn": "BYD",
        "market": "CN",
        "currency": "HKD",
        "theme": ["EV", "AI응용"],
        "description": "세계 1위 전기차·배터리 메이커. '신의 눈' 자율주행 보급에 앞장선다.",
        "beginnerFit": "good",
        "valueChain": "전기차·배터리",
        "exampleTermHints": ["debt-ratio", "beta", "revenue"],
    },
    {
        "ticker": "0981.HK",
        "name": "SMIC(중신국제)",
        "nameEn": "SMIC",
        "market": "CN",
        "currency": "HKD",
        "theme": ["AI반도체", "파운드리"],
        "description": "중국 최대 파운드리. AI 칩 국산화의 핵심 기업.",
        "beginnerFit": "caution",
        "valueChain": "반도체 파운드리",
        "exampleTermHints": ["per", "pbr", "operating-margin"],
    },
    {
        "ticker": "002230.SZ",
        "name": "아이플라이텍(커다페이)",
        "nameEn": "iFlytek",
        "market": "CN",
        "currency": "CNY",
        "theme": ["AI소프트웨어"],
        "description": "중국 AI 국가대표로 불리는 음성인식·스파크(Spark) LLM 소프트웨어 기업.",
        "beginnerFit": "caution",
        "valueChain": "AI 음성·LLM 소프트웨어",
        "exampleTermHints": ["break-even", "psr", "revenue"],
    },
    {
        "ticker": "688256.SS",
        "name": "캠브리콘(한우지)",
        "nameEn": "Cambricon",
        "market": "CN",
        "currency": "CNY",
        "theme": ["AI반도체"],
        "description": "중국 대표 AI 가속기 칩 설계사. 엔비디아 대체 수혜, 극단적 고PER 사례.",
        "beginnerFit": "hard",
        "valueChain": "AI 가속기 칩 설계",
        "exampleTermHints": ["per", "pbr", "week52"],
        "extraRiskFlags": ["극단적 밸류에이션"],
    },
    {
        "ticker": "688066.SS",
        "name": "PIESAT(중국위성응용)",
        "nameEn": "PIESAT Information Technology",
        "market": "CN",
        "currency": "CNY",
        "theme": ["우주-위성응용"],
        "description": "위성 원격탐사 영상을 응용 소프트웨어로 제공하는 중국 위성정보 기업.",
        "beginnerFit": "hard",
        "valueChain": "위성 영상 응용",
        "exampleTermHints": ["psr", "market-cap"],
    },
]
